# Site settings
title: San Franscico Real Estate Video Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Junk Culture
author: Durwin Cheung
twitter:
  username: losslessdesign
facebook:
  app_id:
  publisher:
logo:
social:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Handling Reading
encoding: "utf-8"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

paginate: 4
permalink: none

gems:
  - jemoji
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Excludes
exclude:
  - .sass-cache

sass:
  sass_dir: _sass
  style: :nested
