navigation:
  - title: work
    url: /projects.html
  - title: Contact
    url: /contact.html

title: San Francisco Real Estate Video Blog

client:
  market: Chicago
  name: Joe Somebody
  brand: Castle Greyskull
  brokerage: Keller Williams Realty
  address: '123 Fake St. Eternia, NE'
  phone: 1-234-567-8910
  email: someone@email.com
  url: getvyral.com
  homeeval: '#'
  search: '#'
  VR_form: '#'

socials:
  facebook: '-#'
  linkedin: '-#'
  gplus: '-#'
  youtube: '-#'
  twitter: '-#'
  instagram: '#'
  pinterest: '#'
  zillow: '#'
  trulia: '#'
  yelp: '#'
  podcast: '-#'

review_sm_icons: false

images:
  hero_image_path: /img/sf_downtown.jpg
  hero_logo_path: /img/Durwin_logo_white.png
  hero_background_hex: '#2F3544'
  client_headshot_path: /img/durwin_headshot.png
